// <auto-generated />
namespace Supermarket.Main.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductAvailableIsPositiveCheckMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductAvailableIsPositiveCheckMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201302241112027_ProductAvailableIsPositiveCheckMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
